#ifndef MICROVSA_CONFIG_H_
#define MICROVSA_CONFIG_H_

#define MICROVSA_IMPL_WORDSIZE 32
#define MICROVSA_TMP_DTYPE uint32_t
#define MICROVSA_ACC_DTYPE int32_t
#define MICROVSA_MAX_NUM_CLASS 6
#define MICROVSA_MAX_FHV_DIM 8
#define MICROVSA_MAX_FHV_DIM_BIT 256
#define MICROVSA_IMPL MICROVSA_IMPL_MCU_OPT_CC

// keep large arrays in flash
// #define MODEL_F_IN_RAM
// #define MODEL_V_IN_RAM
// #define MODEL_C_IN_RAM

#endif // MICROVSA_CONFIG_H_
