#ifndef MODEL_MODEL_H_
#define MODEL_MODEL_H_

#include <stdint.h>

#define MICROVSA_MODEL_FHV_DIMENSION_BIT 256
#define MICROVSA_MODEL_FHV_DIMENSION_WORD 8
#define MICROVSA_MODEL_NUM_CLASS 6
#define MICROVSA_MODEL_NUM_FEATURE 561
#define MICROVSA_MODEL_NUM_QUANT 256
#define MICROVSA_MODEL_DTYPE uint32_t

#ifdef MODEL_C_IN_RAM
#define MODEL_C_QUALIFIER
#else
#define MODEL_C_QUALIFIER const
#endif
#ifdef MODEL_F_IN_RAM
#define MODEL_F_QUALIFIER
#else
#define MODEL_F_QUALIFIER const
#endif
#ifdef MODEL_V_IN_RAM
#define MODEL_V_QUALIFIER
#else
#define MODEL_V_QUALIFIER const
#endif

extern MODEL_C_QUALIFIER uint32_t MICROVSA_MODEL_C[];
extern MODEL_F_QUALIFIER uint32_t MICROVSA_MODEL_F[];
extern MODEL_V_QUALIFIER uint32_t MICROVSA_MODEL_V[];

#endif // MODEL_MODEL_H_
